port: 8080
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: "jdbc:postgresql://ec2-54-225-76-136.compute-1.amazonaws.com:5432/d2j55j1bcogqep"
    driverClassName: org.postgresql.Driver
    username: srmxmboalippmb
    password: ac53edabfad1a292658aa209520bb010103e778245a4bec4be9a873259a0d10b
  jpa.hibernate.ddl-auto: create


spring.mvc.dispatch-options-request: true

security.oauth2.client:
  client-id: "squad2"
  client-secret: "secret"
  scope: "password"
  grant-type: "password"
